MAINTAIN "Pedestrian Safety"
    by  "Pedestrian Check" using "Perception Module"
        operationalized as "Detect Pedestrian" performed by "yolov5s"
        taking input "image" producing output "pedestrian detection flag"
    followed by "braking" using "braking module"
        operationalized as "Apply Brakes" if "pedestrian detection flag=True" performed by "proportional_braking"
        taking input "pedestrian detection flag" producing output "Braking Status Flag"
    in scenario where "A pedestrian trying to cross the street in fog."
    assuming "fog_density <= 50" & "pedestrian is on foot, not cycling"
    ensuring "vehicle resumes within 10 s once the crossing is clear"
